# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Honsal's Dailylife with Cream
email: honjasalayo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  크림이와 함께하는 혼살의 일상 및 프로그래밍 블로그에요.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "ko"
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: 
github_username: Honsal
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
